init:
  - ps: if ($env:APPVEYOR_REPO_TAG -eq "true") { $env:TAG_VERSION = "$env:APPVEYOR_REPO_TAG_NAME.$env:APPVEYOR_BUILD_NUMBER" } else { $env:TAG_VERSION = "v3.0.$env:APPVEYOR_BUILD_NUMBER" }
  - ps: $env:TAG_VERSION = $env:TAG_VERSION -replace 'v',''
  - ps: Write-Host "Setting version to '$env:TAG_VERSION'"
  - ps: Update-AppveyorBuild -Version "$env:TAG_VERSION"

environment:
  matrix:
  - job_name: Windows x64 Build
    platform: x64
    appveyor_build_worker_image: Visual Studio 2019
    configuration: ReleaseWindows
  - job_name: Windows x86 Build
    platform: x86
    appveyor_build_worker_image: Visual Studio 2019
    configuration: ReleaseWindows

  BugsplatDatabase: sjofnllc
  PfxDownloadUrl:
    secure: T8uKu+tTR2G7LDE1zPGNOi+prl4YaKXP6DOC5eU6A14FEQkd8PFR3nQ1WMwryphJ
  PfxDownloadPasswd:
    secure: nAIqrjhaoamhiuAcae/xNw==
  PfxPassword:
    secure: +vWSGzLkiBGVIxfPb+iRtD+/maQjI2d92hN4PoNAxMc=

branches:
  except:
    - localbuilding

pull_requests:
  do_not_increment_build_number: true

build:
  project: radegast.sln
  parallel: true
  verbosity: minimal

cache:
  - packages -> **\packages.config
  - '%LocalAppData%\NuGet\Cache'

dotnet_csproj:
  patch: true
  file: '**\*.csproj;**\*.props'
  version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'

before_build:
  - nuget restore radegast.sln
  - ps: util/InstallRemotePfx.ps1 -PfxDownloadUrl $env:PfxDownloadUrl -PfxDownloadUser AppVeyor -PfxDownloadPasswd $env:PfxDownloadPasswd -PfxPasswd $env:PfxPassword

after_build:
  - ps: New-Item -ItemType directory -Path .\$env:PLATFORM
  - cmd: '7z a -ttar -so Radegast-%TAG_VERSION%.tar %APPVEYOR_BUILD_FOLDER%\bin\Release\ | 7z a -si Radegast_%PLATFORM%-%TAG_VERSION%.tbz'
  - ps: Copy-Item bin\Release\RadegastSetup_$env:PLATFORM.msi RadegastSetup_$env:PLATFORM-$env:TAG_VERSION.msi
  - ps: Copy-Item bin\Release\RadegastBundle_$env:PLATFORM.exe RadegastSetup_$env:PLATFORM-$env:TAG_VERSION.exe

artifacts:
  - path: 'RadegastSetup*.exe'
    name: 'Radegast Windows x64 Bundle'
    type: Auto
  - path: 'RadegastSetup*.msi'
    name: 'Radegast Windows x64 MSI'
    type: Auto
  - path: 'Radegast*.tbz'
    name: 'Radegast Linux x64'
    type: Auto
  - path: 'RadegastSetup*.exe'
    name: 'Radegast Windows x86 Bundle'
    type: Auto
  - path: 'RadegastSetup*.msi'
    name: 'Radegast Windows x86 MSI'
    type: Auto
  - path: 'Radegast-*.tbz'
    name: 'Radegast Linux x86'
    type: Auto
  - path: 'bin\Release\Radegast.pdb'
    name: 'Radegast symbols'
    type: Auto
